services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack_s3
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=ap-northeast-2
      - DATA_DIR=/tmp/localstack/data
      - PORT=4566
    volumes:
      - "./localstack_data:/var/lib/localstack"